seed: [ 423626, 737, 246,848, 24787 ]
device: [ cpu ]
root_dir: [ output_causal_nf/comparison_vaca ]
dataset:
  name: 'TODO'
  sem_name: 'TODO'
  root: [ ../Data ]
  splits: [ [ 0.8, 0.1, 0.1 ] ]
  k_fold: [ 1 ]
  shuffle_train: [ True ]
  loss: [ default ]
  scale: [ default ]
  num_samples: [ 25000 ]
  base_version: [ 1 ]
  type: [pyg]
  use_edge_attr: [True]
model:
  name: [ vaca ]
  layer_name: [ gin, pna, pna_disjoint ]
  init: [None]
  act: [relu]
  latent_dim: [4]
  dropout: [0.1, 0.2]
  has_bn: [False]
  plot: [False]
  objective: [elbo]
  beta: [1.0]
  distr_x: [delta]
  lambda_: [0.1]
gnn: # Encoder
  num_layers_pre: [1, 2]
  num_layers: [1]
  num_layers_post: [1]
  dim_inner: [16]
  heads: [1]
  stage_type: [skipsum]
  aggregators: [[ sum, mean, min, max, std ]]
  scalers: [[ identity, amplification, attenuation, linear, inverse_linear ]]
  towers: [1,]
  pre_layers: [1]
  post_layers: [1]
gnn2: # Decoder
  num_layers_pre: [1]
  num_layers: [0]
  num_layers_post: [1]
  dim_inner: [16]
  heads: [1]
  stage_type: [skipsum]
  aggregators: [[ sum, mean, min, max, std ]]
  scalers: [[ identity, amplification, attenuation, linear, inverse_linear ]]
  towers: [1]
  pre_layers: [1]
  post_layers: [1]
train:
  max_epochs: [ 300 ]
  regularize: [ False ]
  batch_size: [ 1024 ]
  inference_mode: [ False ]
  max_time: [ 00:24:00:00 ]
  enable_progress_bar: [ False ]
early_stopping:
  activate: [ False ]
  min_delta: [ 0.0 ]
  patience: [ 100 ]
  verbose: [ False ]
optim:
  optimizer: [ adam ]
  base_lr: [ 5e-3 ]
  beta_1: [ 0.9 ]
  beta_2: [ 0.999 ]
  momentum: [ 0.0 ]
  weight_decay: [ 0.0 ]
  scheduler: [ plateau ]
  mode: [ min ]
  factor: [ 0.95 ]
  patience: [ 60 ]
  cooldown: [ 0 ]