seed: [ 423626, 737, 246,848, 24787 ]
device: [ cpu ]
root_dir: [ output_causal_nf/comparison_x_u ]
dataset:
  name: 'TODO'
  sem_name: 'TODO'
  root: [ ../Data ]
  splits: [ [ 0.8, 0.1, 0.1 ] ]
  k_fold: [ 1 ]
  shuffle_train: [ True ]
  loss: [ default ]
  scale: [ default ]
  num_samples: [ 25000 ]
  base_version: [ 1 ]
model:
  name: [ causal_nf ]
  layer_name: [ maf ]
  dim_inner: [ [ 16, 16, 16 , 16 ],  [ 32, 32, 32 ],  [ 16, 16, 16 ],   [ 32, 32 ],  [ 32 ] , [ 64 ] ]
  num_layers: [ 1 ]
  init: [ None ]
  act: [ elu ]
  adjacency: [ True ]
  base_to_data: [ False ]
  plot: [ False ]
train:
  max_epochs: [ 1000 ]
  regularize: [ False ]
  batch_size: [ 4000 ]
  inference_mode: [ False ]
  max_time: [ 00:24:00:00 ]
  enable_progress_bar: [ False ]
early_stopping:
  activate: [ False ]
  min_delta: [ 0.0 ]
  patience: [ 100 ]
  verbose: [ False ]
optim:
  optimizer: [ adam ]
  base_lr: [ 1e-3 ]
  beta_1: [ 0.9 ]
  beta_2: [ 0.999 ]
  momentum: [ 0.0 ]
  weight_decay: [ 0.0 ]
  scheduler: [ plateau ]
  mode: [ min ]
  factor: [ 0.95 ]
  patience: [ 60 ]
  cooldown: [ 0 ]