device: cpu
root_dir: _models_trained/causal_nf/
seed: 1000
dataset:
  root: New_Data/causal_estimator
  name: loan
  sem_name: linear # non-linear #non-additive
  splits: [ 0.8,0.1,0.1 ]
  k_fold: 1
  shuffle_train: True
  loss: default
  scale: default
  num_samples: 25000
  base_version: 1
model:
  name: causal_nf
  layer_name: maf
  dim_inner: [64]
  num_layers: 1
  init: None
  act: elu
  adjacency: True
  base_to_data: False
  base_distr: normal
  learn_base: False
  plot: False
train:
  max_epochs: 1000
  regularize: False
  kl: forward  # backward
  batch_size: 4000
  num_workers: 0
  limit_train_batches: None
  limit_val_batches: None
  max_time: 00:24:00:00
  inference_mode: False
early_stopping:
  activate: False
  min_delta: 0.0
  patience: 100
  verbose: False
optim:
  optimizer: adam
  base_lr: 0.001
  beta_1: 0.9
  beta_2: 0.999
  momentum: 0.0
  weight_decay: 0.0
  scheduler: plateau
  mode: min
  factor: 0.95
  patience: 60
  cooldown: 0